name: Deploy to VPS via Token

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo with token
        run: |
          git clone https://$GH_DEPLOY_TOKEN@github.com/OliverMunian/L.Distri.git app
        env:
          GH_DEPLOY_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}

      - name: Deploy to VPS via rsync over HTTPS
        run: |
          rsync -avz --delete ./app/ root@${{ secrets.VPS_HOST }}:/opt/sites/ldistri \
            --rsync-path="mkdir -p /opt/sites/ldistri && rsync"
          
          ssh root@${{ secrets.VPS_HOST }} << 'EOF'
            cd /opt/sites/ldistri
            npm install
            npm run build
            pm2 restart ldistri || pm2 start npx --name ldistri -- next start -p 3000
            pm2 save
          EOF